### ISSUE TITLE
deserializeMsgPack method throws exception while using with ASP.NET Core

### ISSUE THREAD

**Issue by anuraj** [ygoe/msgpack.js#1]
I am using msgpack.js with Message Pack implementation in C# for ASP.NET Core. But I am getting an error like this. 

![image](https://user-images.githubusercontent.com/276411/45071673-1922fe80-b0f5-11e8-8faf-3009404fb52a.png)

Here is the code.

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc().AddMvcOptions(option =>
    {
        option.OutputFormatters.Clear();
        option.OutputFormatters.Add(new MessagePackOutputFormatter(StandardResolver.Instance));
        option.InputFormatters.Clear();
        option.InputFormatters.Add(new MessagePackInputFormatter(StandardResolver.Instance));
    }).SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```
And here is the client code.

```
<script src="jquery-3.3.1.min.js"></script>
<script src="msgpack.js"></script>
<script>
    $(function () {
        $.get("/api/person", function (data) {
            console.log(deserializeMsgPack(data));
        });
    });
</script>
```

I am using it in a Web API project, and returning default values controller.

**Comment by ygoe** [comment]
Can you please also log the content of `data` and its type (`typeof(data)`)? This doesn't look like a byte array which it's supposed to be.

**Comment by anuraj** [comment]
It is a complex object. But I tried with simple string, that also not working.

```
[HttpGet("{id}")]
public ActionResult<string> Get(int id)
{
    return "value";
}
```

Here is the response header.

![image](https://user-images.githubusercontent.com/276411/45086000-c448ad80-b11f-11e8-8e59-84d408029958.png)

**Comment by anuraj** [comment]
Okay. Let me try.

**Comment by ygoe** [comment]
Any news here? I can't create a demo project because the type `MessagePackOutputFormatter` cannot be found anywhere. Can you maybe provide a minimal test case for this? I only know about ASP.NET Core 2.1, you seem to use 2.2. Maybe I'll have to wait a bit to run your example.

**Comment by anuraj** [comment]
Oops, my bad. I am able to resolve it. Full details here - https://dotnetthoughts.net/using-message-pack-with-asp-net-core/. Thank you for your response 👍
