### ISSUE TITLE
Encoding in python and decoding in javascript

### ISSUE THREAD

**Issue by vallejohan** [ygoe/msgpack.js#11]
Is it possible to decode an encoded message from python in javascript using this library? And if yes, how?

The encoded message I created in python looks as follow: b'\x83\xa2id\x01\xa4test\x17\xa3hey*'
When I retrieve it in my javascript code and try to deserialize it I get an error message about invalid type, undefined. The encoded message I created in the python script seems to be a Blob{} type when it arrives in the javascript code. I have tried to convert the Blob type to a string by using a fileReader, but with small success.

Any ideas regarding this?

Cheers

**Comment by ygoe** [comment]
Yes, you can decode a MessagePack message everywhere. The specification is language-agnostic and it doesn't matter in which programming language, with what tool or on which type of hardware the data is encoded or decoded.

MessagePack is a binary format. That means it only defines the bytes that a message consists of. This is a different thing than a string. A string, which you showed above, consists of characters, *not* bytes. Characters and bytes are related through a character encoding, like UTF-8, UTF-16 or ISO-8859-15. Such an encoding does not exist in the context of MessagePack (at least for the message as a whole). So when you encode data, you will get a collection of bytes, and you will have to treat it as such. You can only decode the message again if you still have a collection of bytes. How you adequately transport the bytes from your Python output to the JavaScript input depends on what you're doing.

To answer your question, I'd need to see your JavaScript code. Please show me the code you use, and ideally also some dump output like variable types. I'm afraid I can't really help on the Python side as I barely understand such code, let alone find typing issues in there.

**Comment by vallejohan** [comment]
Thank you for the answer, this helps clear things up quite well.

I have attached the javascript code and the output dump from the data sent over from the python script. Let me know if the output dump isn't detailed enough and I'll try to dump more data.

![javascript_code](https://user-images.githubusercontent.com/24614504/53479062-8b5b1700-3a78-11e9-8ba8-06ae6fc70ff9.PNG)
![output_dump](https://user-images.githubusercontent.com/24614504/53479063-8bf3ad80-3a78-11e9-856d-70bb455ed9c0.PNG)

**Comment by ygoe** [comment]
That error message indicates that a byte array contains a value outside the range of a byte (0 to 255). A thing that would be impossible in a statically typed language (like C#) but thanks to dynamic typing in JavaScript, this is very possible. But it tells you that you weren't passing the decode function a byte array but rather an array of something else. Maybe this already helps you a bit further. I'll look into the code closer soon.

**Comment by vallejohan** [comment]
I just found a solution to this issue. I inserted a small function that converts the blob to an arraybuffer, which I then could pass through the deserializeMsgPack to get the correct data.

Thank you for the help of understanding this!

**Comment by ygoe** [comment]
Glad it works now! I guess the input handling of `deserializeMsgPack` could be a little more helpful when it gets the wrong type, like a string.
