### ISSUE TITLE
No "default" case in 'append'

### ISSUE THREAD

**Issue by smurfix** [ygoe/msgpack.js#17]
The encoder's `append` function does not have a default handler. This can result in broken or incomplete objects (e.g. when an encoded object contains a function).

Also, would you consider teaching the encoder to call an object's "toJSON" method (if it has one), and encode its result instead of the original object?

**Comment by ygoe** [comment]
Okay, I see that `appendArray` and single items of `appendObject` can produce invalid MessagePack data. How would you suggest to handle unsupported types? Throwing an error would be the easiest solution, just in the `default` case. Alternatively, those could be replaced by `null` (also simple) or left out (more complex as it affects the caller).

**Comment by smurfix** [comment]
Default: Throw an error. Optional: use an "unpackable=X" option that replaces unpackable objects with X. If X is a function, call it with the object and pack its result.
