### ISSUE TITLE
Add .d.ts typings file

### ISSUE THREAD

**Issue by AArnott** [ygoe/msgpack.js#19]
Can you please add a .d.ts typings file to this package?

**Comment by ygoe** [comment]
@AArnott Could you please suggest a new TypeScript file for the second parameter `options`? It accepts an optional object with the optional keys "multiple" (serialize and deserialize) and "invalidTypeReplacement" (only serialize). I'm not familiar enough with TypeScript to express that.

**Comment by AArnott** [comment]
See #25
