### ISSUE TITLE
Handle NaN and Infinity, set them to Null, like JSON does

### ISSUE THREAD

**Issue by SaulDoesCode** [ygoe/msgpack.js#3]
```js
    function append(data) {
      data == null || data === NaN || data === Infinity ? appendByte(0xc0) :
      (
        data.constructor === String ? appendString :
        data.constructor === Number ? appendNumber :
        data.constructor === Boolean ? appendBoolean :
        Array.isArray(data) ? appendArray :
        data instanceof Date ? appendDate :
        appendObject
      )(data)
    }
```

**Comment by SaulDoesCode** [comment]
Also, thank you for making this. It's really astonishing how you managed to build a whole encoder/decoder with such little code. Compared to msgpack-lite, hah lite (40kb~ minified), this is glorious. Seriously +1 man. 👍

**Comment by ygoe** [comment]
Can you please specify what exactly needs to be converted to what in what function? I just tried to put `NaN` through the test code and got `null` back which seems to be what you're asking for.

**Comment by SaulDoesCode** [comment]
Oh ok 😮, I didn't realize. That's fine then thanks.

**Comment by SaulDoesCode** [comment]
Wait I'm confused. Does the old code handle this or not?

**Comment by SaulDoesCode** [comment]
[Here's my adaptation of this library.](https://gist.github.com/SaulDoesCode/93953005e60256c0ed11e18e7cf74b23)

I'm not sure if the original handles those types mentioned, but, in my derivative version I added the checks. 

This issue was just a heads up in case someone accidentally tries to serialize one of javascripts weird falsey/nully values and the thing crashes.

Sorry for the confusion and trouble.

**Comment by ygoe** [comment]
I haven't compared your code with mine so I don't know where the differences are.

But I still don't understand what exactly you need to be converted. NaN to MsgPack to JavaScript gives me null. That doesn't say anything about what the MsgPack data looks like. If JS to MsgPack converts NaN to null, then MsgPack to JS doesn't need to do anything. If you have existing MsgPack with a special value and convert to JS, then something else might happen.

**Comment by ygoe** [comment]
But then again, the MsgPack spec says it includes NaN and infinity values, but doesn't explain what bits they have. So I'm not sure how to implement this. And there's no special code in msgpack.js, it's all done by a DataView object. So it should probably preserve these special values. Converting to null is probably not correct here.

**Comment by SaulDoesCode** [comment]
Hmm, that's interesting I'll just remove the checks then and let DataView figure it out as you say. Thanks.
