### ISSUE TITLE
Wrong array serialization

### ISSUE THREAD

**Issue by fix** [ygoe/msgpack.js#33]
Hi i came across a serious issue that breaks the specs:
0xf should be 0xff instead

here: https://github.com/ygoe/msgpack.js/blob/master/msgpack.js#L172

and here: https://github.com/ygoe/msgpack.js/blob/master/msgpack.js#L190

**Comment by fix** [comment]
see here (https://github.com/msgpack/msgpack-javascript/blob/main/src/Encoder.ts#L313)
`< 0x100` <=> `<=0xff`

**Comment by ygoe** [comment]
Thanks, fixed. The second line you mentioned (190) is correct though.

**Comment by fix** [comment]
true that. Thanks for the fix
