### ISSUE TITLE
Does it work with System.Decimal?

### ISSUE THREAD

**Issue by NetDefender** [ygoe/msgpack.js#8]
Hello
First of all great work. Im using **.Net Core** as backend, and im interested knowing if is possible to have decimal values in **C#** class or is mandatory to use double.
Thanks in advance

**Comment by ygoe** [comment]
That really doesn't matter. Both the .NET types `Double` and `Decimal` support floating point numbers within a certain value range. They're not the same, but neither is the same as the range supported by JavaScript's number type.

Anyway, msgpack.js is a JavaScript library, it runs purely in JavaScript and doesn't have any contact with C# or other languages. So when you pass data from one to the other, it needs to be done by other means, like serialisation to a string, for example JSON. Both double and decimal numbers have the same string representation.

Also, MessagePack has [no special support](https://github.com/msgpack/msgpack/blob/master/spec.md#formats) for a "decimal" type. All it knows is integer and floating point numbers of a certain length (and thereby value range). "float 32" should be the same a C#'s `float` (.NET `Single`) and "float 64" is the `double` type.

So, you can use whatever type on your backend side as you wish: float, double, decimal. It needs to meet the requirements that exist on that side. MsgPack has separate types and the msgpack.js library can only use what JavaScript can handle.

I hope that I have understood you correctly and this answers your question.
