### ISSUE TITLE
Date deserialisation doesn't cope with pre-epoch dates

### ISSUE THREAD

**Issue by adamrodger** [ygoe/msgpack.js#9]
If you serialise a date which is pre-epoch, e.g. `new Date(-1)` is `1969-12-13 23:59:59.999`, and then attempt to deserialize it, the deserialsiation fails return the same date.

![image](https://user-images.githubusercontent.com/508586/51848172-fcda6500-2314-11e9-9d58-650d345b2cc0.png)

Hex representation:

![image](https://user-images.githubusercontent.com/508586/51848428-7bcf9d80-2315-11e9-8d52-faed9dcc39cb.png)

From a quick play around in the debugger this appears to be because the sign bit and 2's compliment is not respected for negative numbers (which are required for pre-epoch times). My guess is that this is due to the bit shifting required to parse the dates.

**Comment by ygoe** [comment]
Thank you for the report. I have verified the issue and switched to using existing int64 code for the seconds part of pre-epoch dates.
